### ISSUE TITLE
Allow hlint to be found by stack exec

### ISSUE THREAD

**Issue by dmp1ce** [purcell/flymake-hlint#1]
If `hlint` has been installed with `stack build --copy-compiler-tool hlint` then `hlint` will not be found. It would be nice if `stack exec` could be checked for `hlint` without needing to put `hlint` in the `PATH`.

I'm posting issue here because of a issue with Spacemacs I had: https://github.com/syl20bnr/spacemacs/issues/11132

**Comment by purcell** [comment]
That's a long way out of scope for this package, since it's already possible to customise the executable as needed, but in general the thing to do when working in Stack projects is to add Stack's bin path to each buffer in the project. I have a hack to do just that [here](https://github.com/purcell/emacs.d/blob/de5551212dff3530dcccef4085ff0d2349844c0f/lisp/init-haskell.el#L59-L77).

**Comment by purcell** [comment]
That's a long way out of scope for this package, since it's already possible to customise the executable as needed, but in general the thing to do when working in Stack projects is to add Stack's bin path to each buffer in the project. I have a hack to do just that [here](https://github.com/purcell/emacs.d/blob/de5551212dff3530dcccef4085ff0d2349844c0f/lisp/init-haskell.el#L59-L77).
